language: java

jdk:
  - oraclejdk8

install: true

#script: "mvn install -Dmaven.javadoc.skip=true -B -V"

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
